version: '3.8'

services:
  app1: 
    image: nando2302/tangkasnginx:1.0
    networks:
      backend:
        ipv4_address: 172.10.10.10

    ports:
      - target: 80
        published: 80
        protocol: tcp

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  app2: 
    image: nando2302/tangkasnginx:1.0
    ports:
      - target: 80
        published: 80
        protocol: tcp
    networks:
      backend:
        ipv4_address: 172.10.10.11

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  lb-nginx:
    image: nando2302/lb-react:3.0
    networks:
      backend:
        ipv4_address: 172.10.10.9

    ports:
      - target: 80
        published: 80
        protocol: http
    
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  backend:
    # ipam:
    #   driver: overlay
    #   subnet: "172.10.10.0/24"
