version: '3.8'
services:

  app:
    # container_name: react-nginx
    image: nando2302/tangkasnginx:1.0
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 60s
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback