version: '3.7'
services:

  app:
    container_name: react-nginx
    image: nando2302/tangkasnginx:1.0
    ports:
      - 80:81
    restart: 
      on-failure
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure