version: '3.8'

services:
  app: 
    image: nando2302/tangkasnginx:1.0
    ports:
      - target: 80
        published: 80
        protocol: tcp

    deploy:
      mode: replicated
      replicas: 2
      update_config:
      