version: '3.8'
services:

  react-app:
    image: nando2302/tangkasnginx:1.0
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
    
  loadbalancer:
    image: nando2302/lb-react:1.0
    ports:
    - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 0
        delay: 10s
        failure_action: rollback
      placement:
        constraints: [node.role == manager]
