version: '3.8'
services:
  web-server1:
    image: nando2302/tangkasnginx:1.0
    networks:
      backend:
       ipv4_address: { 10.1.5.8, 10.1.5.9}
    ports:
      - target: 80
        published: 80
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 2

      restart_policy:
        condition: on-failure

  lb-nginx:
    image: nando2302/lb-nginxst:1.0
    networks:
      backend:
        ipv4_address: 10.1.5.7
    ports:
      - target: 80
        published: 8080
        protocol: tcp

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 10.1.5.0/24