version: '3.8'
services:
  web-server1:
    image: nando2302/tangkasnginx:1.0

    ports:
      - target: 80
        published: 81
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 1

      restart_policy:
        condition: on-failure
  web-server2:
    image: nando2302/tangkasnginx:1.0
    
      
    ports:
      - target: 80
        published: 82
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 1

      restart_policy:
        condition: on-failure

  lb-nginx:
    image: nando2302/lb-nginxst:1.0
    depends_on:
      - webserver1
      - webserver2
    ports:
      - target: 80
        published: 8080
        protocol: tcp

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

