version: '3.8'
services:

  app:
    # container_name: react-nginx
    image: nando2302/tangkasnginx:1.0
    ports:
      - 80:80
    restart: 
      on-failure
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
