version: '3.8'
services:

  react-app:
    image: nando2302/tangkasnginx:1.0
    ports:
      - target: 80
        published: 80
        protocol: tcp
        # mode: host
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
        

  loadbalancer:
    image: nando2302/lb-react:1.0
    ports:
      - target: 8080
        published: 8080
        protocol: http
    deploy:
      # mode: global
      update_config:
        parallelism: 0
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]
